import { uid } from "./utils";
import type { InventoryItem, StorageBin } from "./types";

export const DEFAULT_BINS: StorageBin[] = [
  { id: "bin_receiving", name: "Receiving", zone: "Intake" },
  { id: "bin_aisle_a", name: "Aisle A", zone: "Warehouse" },
  { id: "bin_aisle_b", name: "Aisle B", zone: "Warehouse" },
  { id: "bin_overflow", name: "Overflow", zone: "Back" },
];

type SampleSeed = Omit<InventoryItem, "id" | "createdAt" | "source" | "status">;

const SEEDS: SampleSeed[] = [
  {
    name: "Herman Miller Aeron, size B",
    category: "Furniture",
    brand: "Herman Miller",
    condition: "good",
    description:
      "Classic Aeron in graphite, size B. Mesh intact, arm pads worn, cylinder still holds. A desk chair with years left.",
    quantity: 1,
    marketLow: 280,
    marketMid: 420,
    marketHigh: 560,
    priceBasis: "Used size-B Aerons commonly list $300–550 on Facebook Marketplace and Craigslist.",
    listingPercent: 80,
    storageId: "bin_aisle_a",
    notes: "Needs a wipe-down before photos.",
  },
  {
    name: "Nintendo Switch OLED",
    category: "Electronics",
    brand: "Nintendo",
    condition: "like-new",
    description:
      "White OLED model with dock, both Joy-Con, HDMI and USB-C. Screen is clean, no drift reported.",
    quantity: 1,
    marketLow: 180,
    marketMid: 220,
    marketHigh: 250,
    priceBasis: "Complete OLED units typically sit $190–240 used on eBay and Marketplace.",
    listingPercent: 80,
    storageId: "bin_aisle_b",
    notes: "",
  },
  {
    name: "Le Creuset Dutch oven, 5.5 qt",
    category: "Kitchen",
    brand: "Le Creuset",
    condition: "good",
    description:
      "Flame-orange round Dutch oven. Enamel is largely intact with light interior staining. Lid fits true.",
    quantity: 1,
    marketLow: 120,
    marketMid: 175,
    marketHigh: 230,
    priceBasis: "Used 26cm / 5.5 qt Le Creuset casseroles list around $140–220 depending on color.",
    listingPercent: 75,
    storageId: "bin_aisle_a",
    notes: "",
  },
  {
    name: "Sony WH-1000XM4 headphones",
    category: "Electronics",
    brand: "Sony",
    condition: "good",
    description:
      "Black XM4s with case and charging cable. Ear pads original, ANC works. Light headband wear.",
    quantity: 1,
    marketLow: 90,
    marketMid: 120,
    marketHigh: 150,
    priceBasis: "Used XM4s with case typically $100–140 on eBay sold listings.",
    listingPercent: 80,
    storageId: "bin_aisle_b",
    notes: "",
  },
  {
    name: "Trek FX 2 hybrid bike",
    category: "Sporting",
    brand: "Trek",
    condition: "fair",
    description:
      "Large-frame FX 2, disc brakes, some cable rust and scuffed fork. Tires hold air. Solid commuter.",
    quantity: 1,
    marketLow: 160,
    marketMid: 220,
    marketHigh: 280,
    priceBasis: "Used FX 2 hybrids in rideable shape list $180–280 locally.",
    listingPercent: 70,
    storageId: "bin_overflow",
    notes: "Needs a gear tune before listing photos.",
  },
  {
    name: "Canon AE-1 35mm camera",
    category: "Collectibles",
    brand: "Canon",
    condition: "good",
    description:
      "AE-1 body with 50mm f/1.8 FD lens. Shutter fires, light seals original, light meter untested with fresh battery.",
    quantity: 1,
    marketLow: 80,
    marketMid: 125,
    marketHigh: 170,
    priceBasis: "Working AE-1 + 50mm kits commonly $90–160 on eBay.",
    listingPercent: 85,
    storageId: "bin_aisle_b",
    notes: "",
  },
  {
    name: "Patagonia Nano Puff, men's M",
    category: "Apparel",
    brand: "Patagonia",
    condition: "like-new",
    description:
      "Forge grey Nano Puff jacket, men's medium. Zipper clean, no snags, faint wear at cuffs.",
    quantity: 1,
    marketLow: 70,
    marketMid: 95,
    marketHigh: 130,
    priceBasis: "Used Nano Puffs in M list $80–120 on Poshmark and Marketplace.",
    listingPercent: 80,
    storageId: "bin_aisle_a",
    notes: "",
  },
  {
    name: "Craftsman 200-pc mechanics set",
    category: "Tools",
    brand: "Craftsman",
    condition: "good",
    description:
      "Mixed SAE/metric socket set in the original blow-mold case. A few 10mm sockets missing; ratchets feel tight.",
    quantity: 1,
    marketLow: 35,
    marketMid: 55,
    marketHigh: 80,
    priceBasis: "Incomplete Craftsman mechanic sets usually $40–70 at garage-sale/resale prices.",
    listingPercent: 80,
    storageId: "bin_receiving",
    notes: "Photograph the missing-piece tray so buyers aren't surprised.",
  },
  {
    name: "Pair of brass candlesticks",
    category: "Decor",
    brand: "",
    condition: "good",
    description:
      "Turned brass candlesticks, about 10 inches. Nice patina, one slight lean. Weighted bases.",
    quantity: 2,
    marketLow: 24,
    marketMid: 40,
    marketHigh: 65,
    priceBasis: "Pairs of mid-century brass sticks typically $30–60 on Etsy and Marketplace.",
    listingPercent: 80,
    storageId: "bin_aisle_a",
    notes: "",
  },
  {
    name: "Dyson V8 cordless vacuum",
    category: "Appliances",
    brand: "Dyson",
    condition: "fair",
    description:
      "V8 with motorized floor head and crevice tool. Battery holds ~12 minutes. Filter recently rinsed.",
    quantity: 1,
    marketLow: 60,
    marketMid: 90,
    marketHigh: 130,
    priceBasis: "Used V8s with working battery commonly $70–120.",
    listingPercent: 75,
    storageId: "bin_overflow",
    notes: "",
  },
  {
    name: "IKEA Billy bookcase, white",
    category: "Furniture",
    brand: "IKEA",
    condition: "good",
    description:
      "Standard 80cm Billy in white. Backboard intact, a few shelf-pin holes worn. Disassembled and bagged.",
    quantity: 1,
    marketLow: 20,
    marketMid: 35,
    marketHigh: 50,
    priceBasis: "Used Billys move at $20–45 curbside / Marketplace.",
    listingPercent: 80,
    storageId: "bin_overflow",
    notes: "Hardware in a labeled bag taped to a shelf.",
  },
  {
    name: "Pyrex primary-color mixing bowls",
    category: "Kitchen",
    brand: "Pyrex",
    condition: "good",
    description:
      "Nest of four primary-color Pyrex mixing bowls. No chips; yellow bowl has a faint utensil scratch.",
    quantity: 1,
    marketLow: 40,
    marketMid: 70,
    marketHigh: 110,
    priceBasis: "Complete primary nests often $50–100 depending on shine and chips.",
    listingPercent: 85,
    storageId: "bin_aisle_a",
    notes: "",
  },
];

export function makeSampleLot(): InventoryItem[] {
  const now = Date.now();
  return SEEDS.map((seed, i) => ({
    ...seed,
    id: uid("item"),
    source: "sample" as const,
    status: "stored" as const,
    createdAt: now - i * 36_000,
  }));
}
